# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c26f5fb947fabe076183ef3aca9d6aefcfa28e40fdf994c8df9e31d1a993953b8f88dad2deaf546c0d8482a9ba0e78a8bbeae9bc23a7a65fac0539cbbebcfeff

test:
  secret_key_base: 6ffbe352168adbd89e0d79f0ef73d17426c7f56fd0cbfc53d9dcaa74218fb4abefedf20cf29814d8404708e64530ffe381358e786a612734085d4b0ad9f48606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
